### ISSUE TITLE
window.device undefined on app startup

### ISSUE THREAD

**Issue by fernandomg** [AlexDisler/ng-persist#1]
Hello Alex,

I was testing this plugin on a moto-e (android 4.4) device using IonicFramework.

I'm getting the error "TypeError: Cannot read property 'platform' of undefined" on line 16 of ng-persist.js

The workaround that I found was to wrap with a setTimeout of 1000 ms the block between lines 13 and 18 ([link](https://github.com/AlexDisler/ng-persist/blob/master/src/ng-persist.js#L13-L18)), based on this [stackoverflow answer] (http://stackoverflow.com/a/5827402).

Please let me know if there is another workaround to this.

Best regards!

**Comment by AlexDisler** [comment]
Hi,

It happens because the angular code is executed before the device is ready. Try this:

```js
angular.element(document).ready(() => {
  if (window.cordova) {
    document.addEventListener('deviceready', () => {
      angular.bootstrap(document.body, ['app']);
    }, false);
  } else {
    angular.bootstrap(document.body, ['app']);
  }
});
```
And remove the ng-app directive from your html.
