### ISSUE TITLE
Update plugin to work with new KeychainPlugin

### ISSUE THREAD

**Issue by jacquesdev** [AlexDisler/ng-persist#6]
https://github.com/shazron/KeychainPlugin is now obsolete, ensure plugin works with this one instead https://github.com/driftyco/cordova-plugin-ios-keychain as per the readme.

**Comment by jacquesdev** [comment]
For what it's worth - I am working on this, so expect a PR early next week.

**Comment by HeyHugo** [comment]
Have you made any progress on this?

I believe I might be facing the same issue I saw you wrote about on new KeychainPlugin
```
Object is not a constructor (evaluating 'new window.Keychain')
```

**Comment by jacquesdev** [comment]
Hi @HeyHugo - I have unfortunately not worked on this since August, because I was waiting for a few bugs to be fixed in the new Keychain Plugin, which I think are now complete.

It looks like I made some changes, but never added the PR (never tested it). You can test it here:
https://github.com/OLIOEX/ng-persist.

I will add the PR here as well, perhaps you can let me know if it worked?

**Comment by HeyHugo** [comment]
Hi!

I can confirm your fork is fixing this issue. Great work, thanks!
